name: Release

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

concurrency:
  group: ${{ github.workflow }}-release-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  style:
    uses: ./.github/workflows/code-style.yml

  test:
    uses: ./.github/workflows/test-template-build.yml

  release:
    needs: [style, test]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref_name }}

      - name: Force release branch to be at workflow sha
        run: |
          git reset --hard ${{ github.sha }}

      - name: Run python-semantic-release
        id: release
        uses: python-semantic-release/python-semantic-release@9a026e9303981c866c3425723009becb2437c757 # v10.6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: releaserc.toml

      - name: Publish release
        uses: python-semantic-release/publish-action@6d89e2de8d40ecb3717316ecbbf15a6fa8ea9039 # v10.6.2
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

    outputs:
      released: ${{ steps.release.outputs.released || 'false' }}
